name: "PR Labeling"
on: pull_request_target
  
permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("Payload is " + JSON.stringify(context.payload, null, 2))
            if (context.payload.pull_request.base_ref.includes("main"))
            {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['Label']
              })
            }